version: '3.7'
services:
  licensingservice:
    image: license-server:latest
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:    # 서비스가 속한 네트워크 이름을 지정한다.
        aliases:
          - "licenseservice"  # 네트워크 상에서 이 서비스에 대한 대체 호스트 이름을 지정한다.

networks:
  backend:     # 커스텀 네트워크의 이름. default는 bridge이다.
    driver: bridge