server:
  port: 8070  # listening port for the Eureka Server

eureka:
  instance:
    hostname: eurekaserver  # the Eureka instance hostname
  client:
    register-with-eureka: false   # Config Server가 Eureka 서버에 등록하지 않도록 한다.
    fetch-registry: false         # Config Server가 로컬에 레지스트리 정보를 캐시하지 않도록 한다.
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"