version: '3.7'
services:
  configserver:
    image: config-server:latest
    ports:
      - "8071:8071"
    networks:
      backend:    # 서비스가 속한 네트워크 이름을 지정한다.
        aliases:
          - "configserver"  # 네트워크 상에서 이 서비스에 대한 대체 호스트 이름을 지정한다.

networks:
  backend:     # 커스텀 네트워크의 이름. default는 bridge이다.
    driver: bridge